package:
  name: mpfr
  version: 3.1.3

source:
  fn: mpfr-3.1.3.tar.xz
  url: http://www.mpfr.org/mpfr-current/mpfr-3.1.3.tar.xz

requirements:
  build:
    - gmp
  run:
    - gmp


about:
  home: http://www.mpfr.org/
  license: LGPL
  summary: The MPFR library is a C library for multiple-precision floating-point computations with correct rounding.
